### ISSUE TITLE
split into producer/consumer

### ISSUE THREAD

**Issue by etnt** [klarna/system_monitor#28]
Hi,

Very nice application!

Here is just a thought: it would be nice to split it into a producer that dig up the info, then post it (as e.g json) via HTTP to an accompanying consumer that then talks to Postgres.

This way, you would restrict the amount of code that need to run on your production machine.

Hey, I might even implement it myself someday... ;-)

Cheers, Tobbe

**Comment by mikpe** [comment]
Can't you achieve that by configuring your own callback module?

**Comment by etnt** [comment]
Aha...ok, I see what you mean now (been sidetracked a couple of months...).
I'll look into it. 
Btw: what is the reason for the use of that `supervisor3` module?

**Comment by mikpe** [comment]
> Btw: what is the reason for the use of that `supervisor3` module?

I suspect the author was simply following a common in-house pattern when writing this. Off-hand I don't see why plain OTP `supervisor` wouldn't work here.

**Comment by etnt** [comment]
I've got something working now if anyone is interested.

It hardly affectes the existing code base at all, just some
stuff in system_monitor_sup.erl that shouldn't affect anyone.

I'm not quite ready to issue a merge-request yet but you can
read more about it here: 

https://github.com/etnt/system_monitor/blob/master/CONSUMER_PRODUCER.md

Cheers, Tobbe

**Comment by etnt** [comment]
fyi: I've now also added a way to add custom metrics. See: https://github.com/etnt/system_monitor/blob/master/CUSTOM_METRICS.md
